# YAML formatted configuration file for NotifBot
server: 'irc.opoy.fi'
port: '6667'
nick: 'notif'
realname: 'Simple notification bot'
channel: '#NotifBot-test'

# Configuration for SimpleRss plugin
SimpleRss:
        urls:
        - "http://www.raippa.fi/RecentChanges?action=rss_rc&unique=1"
